apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: personal-website  # Make this match the label in template
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
      - name: personal-website
        image: will7i7am7/personal-website:v1
