name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/personal-website:v1 .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/personal-website:v1

    - name: Deploy to Linode
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USERNAME }}
        password: ${{ secrets.LINODE_SSH_PASSWORD }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/personal-website:v1
          docker stop my-container || true
          docker rm my-container || true
          docker run -d --name my-container ${{ secrets.DOCKER_HUB_USERNAME }}/personal-website:v1
